const response = {
    cardId:1,
    eventDetails:{
        date:'date',
        time:'time',
        location:'location',
        subEvents:[
            {
                sub_eventId:1,
                sub_eventName:"Haldi",
                time:'date',
                date:'date',
                location:''
            },
            {
                sub_eventId:2,
                sub_eventName:"Sangit",
                time:'date',
                date:'date',
                location:''
            }
        ]
    },
    groomDetails:{
        firstName:'firstName',
        lastName:'lastName',
        imageUrl:'imageUrl',
        parentDetails:[
            {
                firstName:'firstName',
                lastName:'lastName',
                relationWithGroom:'relationWithGroom'
            },
            {
                firstName:'firstName',
                lastName:'lastName',
                relationWithGroom:'relationWithGroom'
            }
        ],
        socialMediaLinks:[
            {
                socialMediaName:Facebook,
                profileUrl:'profileUrl',
            },
            {
                socialMediaName:Instagram,
                profileUrl:''
            }
        ]
    },
    brideDetails:{
        firstName:'firstName',
        lastName:'lastName',
        imageUrl:'',
        parentDetails:[
            {
                firstName:'',
                lastName:'',
                relationWithGroom:''
            }
        ],
        socialMediaLinks:[
            {
                socialMediaName:Facebook,
                profileUrl:''
            }
        ]
    },
    galleryDetails:[
        {},{},{}
    ],
    videoGalleryDetails:[
        {},{}, {}
    ],
    InviterDetails:{
        firstName:'firstName',
        lastName:'lastName',
        email:'email',
        contactNumber:'contactNumber',
        whatsappName:'whatsappName',
        location:'location'
    },
    backgroundMusicDetails:{
        audioFileSrc:'url',
    }
}