export const UPDATE_EVENT_FIELD_DETAILS = 'UPDATE_EVENT_FIELD_DETAILS';
export const UPDATE_FORM_ERROR = 'UPDATE_FORM_ERROR';


// create a new event card
// c--> Create
export const C_SAVE_EVENT_FIELD_DETAILS = 'C_SAVE_EVENT_FIELD_DETAILS';
export const C_SAVE_EVENT_NAME = 'C_SAVE_EVENT_NAME';
export const C_SAVE_EVENT_DATE = 'C_SAVE_EVENT_DATE';
export const C_SAVE_BRIDE_AND_GROOM_BASIC_DETAILS = 'C_SAVE_BRIDE_AND_GROOM_BASIC_DETAILS';
export const C_SAVE_MEDIA_DETAILS = 'C_SAVE_MEDIA_DETAILS';
export const C_IMAGE_UPLOAD_DONE_FOR_BRIDE = 'C_IMAGE_UPLOAD_DONE_FOR_BRIDE'
export const C_SAVE_ENGAGEMENT_DATE = 'C_SAVE_ENGAGEMENT_DATE'
export const C_SAVE_ENGAGEMENT_TIME = 'C_SAVE_ENGAGEMENT_TIME'


export const PROCEED_TO_NEXT_PAGE = 'PROCEED_TO_NEXT_PAGE';
export const RESET_CURRENT_PAGE_TO_ONE = 'RESET_CURRENT_PAGE_TO_ONE';
export const RESET_TEMP_NEW_CARD_DATA = 'RESET_TEMP_NEW_CARD_DATA';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';