export const UPDATE_EVENT_FIELD_DETAILS = 'UPDATE_EVENT_FIELD_DETAILS';
export const UPDATE_FORM_ERROR = 'UPDATE_FORM_ERROR';


// create a new event card
// c--> Create
export const C_SAVE_EVENT_FIELD_DETAILS = 'C_SAVE_EVENT_FIELD_DETAILS';
export const C_SAVE_EVENT_NAME = 'C_SAVE_EVENT_NAME';
export const C_SAVE_EVENT_DATE = 'C_SAVE_EVENT_DATE';
export const C_SAVE_BRIDE_AND_GROOM_BASIC_DETAILS = 'C_SAVE_BRIDE_AND_GROOM_BASIC_DETAILS';
export const C_SAVE_MEDIA_DETAILS = 'C_SAVE_MEDIA_DETAILS';
export const C_IMAGE_UPLOAD_DONE_FOR_BRIDE = 'C_IMAGE_UPLOAD_DONE_FOR_BRIDE'
export const C_SAVE_ENGAGEMENT_DATE = 'C_SAVE_ENGAGEMENT_DATE'
export const C_SAVE_ENGAGEMENT_TIME = 'C_SAVE_ENGAGEMENT_TIME'
export const C_SAVE_EVENT_TIME = 'C_SAVE_EVENT_TIME'
export const C_SAVE_ACTUAL_IMAGE = 'C_SAVE_ACTUAL_IMAGE'
export const C_DELETE_ACTUAL_IMAGE = 'C_DELETE_ACTUAL_IMAGE'
export const C_SAVE_EVENT_ADDRESS = 'C_SAVE_EVENT_ADDRESS'
export const C_SAVE_ENGAGEMENT_ADDRESS = 'C_SAVE_ENGAGEMENT_ADDRESS'
export const C_ENGAGEMENT_ADDRESS_SAME_AS_WEDDING = 'C_ENGAGEMENT_ADDRESS_SAME_AS_WEDDING'
export const C_TOGGLE_ADD_ENGAGEMENT_DETAILS = 'C_TOGGLE_ADD_ENGAGEMENT_DETAILS'

export const C_SAVE_SANGEET_DATE = 'C_SAVE_SANGEET_DATE'
export const C_SAVE_SANGEET_TIME = 'C_SAVE_SANGEET_TIME'
export const C_SAVE_SANGEET_ADDRESS = 'C_SAVE_SANGEET_ADDRESS'
export const C_SANGEET_ADDRESS_SAME_AS_WEDDING = 'C_SANGEET_ADDRESS_SAME_AS_WEDDING'
export const C_TOGGLE_ADD_SANGEET_DETAILS = 'C_TOGGLE_ADD_SANGEET_DETAILS'

export const C_SAVE_HALDI_DATE = 'C_SAVE_HALDI_DATE'
export const C_SAVE_HALDI_TIME = 'C_SAVE_HALDI_TIME'
export const C_SAVE_HALDI_ADDRESS = 'C_SAVE_HALDI_ADDRESS'
export const C_HALDI_ADDRESS_SAME_AS_WEDDING = 'C_HALDI_ADDRESS_SAME_AS_WEDDING'
export const C_TOGGLE_ADD_HALDI_DETAILS = 'C_TOGGLE_ADD_HALDI_DETAILS'



export const C_TOGGLE_ADD_PARENT_DETAILS = 'C_TOGGLE_ADD_PARENT_DETAILS'
export const C_SAVE_BRIDE_PARENT_DETAILS = 'C_SAVE_BRIDE_PARENT_DETAILS'
export const C_SAVE_GROOM_PARENT_DETAILS = 'C_SAVE_GROOM_PARENT_DETAILS'
export const C_SAVE_BRIDE_PARENT_ACTUAL_IMAGE = 'C_SAVE_BRIDE_PARENT_ACTUAL_IMAGE'
export const C_SAVE_GROOM_PARENT_ACTUAL_IMAGE = 'C_SAVE_GROOM_PARENT_ACTUAL_IMAGE'

export const C_DELETE_ACTUAL_IMAGE_BRIDE_PARENT = 'C_DELETE_ACTUAL_IMAGE_BRIDE_PARENT'
export const C_DELETE_ACTUAL_IMAGE_GROOM_PARENT = 'C_DELETE_ACTUAL_IMAGE_GROOM_PARENT'

export const C_CLEAR_PARENT_DETAILS = 'C_CLEAR_PARENT_DETAILS'
export const C_CHANGE_PRIORITY_BETWEEN_PARENTS = 'C_CHANGE_PRIORITY_BETWEEN_PARENTS'
export const C_CHANGE_PRIORITY_BETWEEN_BRIDE_AND_GROOM = 'C_CHANGE_PRIORITY_BETWEEN_BRIDE_AND_GROOM'
export const C_SAVE_EVENT_ADDRESS_GOOGLE_MAP_LINK = 'C_SAVE_EVENT_ADDRESS_GOOGLE_MAP_LINK'
export const C_UPDATE_GALLERY_DETAILS = 'C_UPDATE_GALLERY_DETAILS'

// photo gallery is what takes images from user
export const C_SAVE_PHOTO_GALLERY = 'C_SAVE_PHOTO_GALLERY'
export const C_DELETE_PHOTO_FROM_GALLERY = 'C_DELETE_PHOTO_FROM_GALLERY'
export const TOGGLE_REJECT_DEFAULT_AUDIO_FILES = 'TOGGLE_REJECT_DEFAULT_AUDIO_FILES'
export const UPDATE_SELECTED_AUDIO_INDEX = 'UPDATE_SELECTED_AUDIO_INDEX'
export const UPDATE_SELECTED_AUDIO_DETAILS = 'UPDATE_SELECTED_AUDIO_DETAILS'
export const SAVE_USER_AUDIO_FILE = 'SAVE_USER_AUDIO_FILE'

export const PROCEED_TO_NEXT_PAGE = 'PROCEED_TO_NEXT_PAGE';
export const RESET_CURRENT_PAGE_TO_ONE = 'RESET_CURRENT_PAGE_TO_ONE';
export const RESET_TEMP_NEW_CARD_DATA = 'RESET_TEMP_NEW_CARD_DATA';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';

// update
export const C_CHANGE_PRIORITY_BETWEEN_FAMILY = 'C_CHANGE_PRIORITY_BETWEEN_FAMILY'
export const C_TOGGLE_ADD_FAMILY_DETAILS = 'C_TOGGLE_ADD_FAMILY_DETAILS'
export const C_SAVE_FAMILY_ARRAY = 'C_SAVE_FAMILY_ARRAY'